# TensorFlow Fundamentals

In this notebook we will cover the fundamentals of the TensorFlow. More specifically:

- Introduction to tensors,
- Getting information from tensors,
- Manipulating tensors,
- Tensors & NumPy,
- Using GPUs with TensorFlow (or TPUs),
- Exercises to try.

## 1. Introduction to tensors

In [1]:
import tensorflow as tf
print(tf.__version__)
print("GPUs:", tf.config.list_physical_devices('GPU'))

2.19.1
GPUs: []


### Create a tensor with tf.constant()

In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of the tensor.
scalar.ndim

0

In [4]:
# Create a vector.
vector = tf.constant([1, 1])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1], dtype=int32)>

In [5]:
# check the ndim.
vector.ndim

1

In [6]:
# Create a matrix.
matrix = tf.constant([[1, 2], 
                      [3, 4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Create another matrix. 
# Specify the dtype of the atrix elements.
another_matrix = tf.constant([[2., 3.],
                             [5., 4.],
                             [7., 3.]], dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[2., 3.],
       [5., 4.],
       [7., 3.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
# Create a tensor.
# Note how complicated it is to write down a tensor.
tensor = tf.constant([[[5, 6], 
                       [3, 3]],
                      [[2, 4], 
                       [1, 7]]])
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[5, 6],
        [3, 3]],

       [[2, 4],
        [1, 7]]], dtype=int32)>

In [11]:
tensor.ndim

3

### Create a tensor with tf.Variable()

In [12]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [13]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# Let's try to change one of the element.
changeable_tensor[0] = 7    # This does not work!

TypeError: 'ResourceVariable' object does not support item assignment

In [15]:
# Let's try with assing()
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [16]:
# Let's try to change the unchangeable_tensor.
# unchangeable_tensor[0] = 7    # This does not work!

In [17]:
# Let's try with assign()
# unchangeable_tensor[0].assign(7)   # This also does not work.

With tf.constant() you cannot change the values, while with tf.Variable() the values are changeable.

### Create a random tensor

In [1]:
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'
import tensorflow as tf

In [ ]:
# The code below does not work, kernel is dying. It may be related to some incompatible versions of packages, use of macos or something else.

### Shuffle the elements of the tensor (needed when the initial order of elements should not affect the output)

In [2]:
not_shuffled = tf.constant([[10, 7],
                            [4, 5],
                            [3, 6]])

In [3]:
not_shuffled.ndim

2

In [11]:
# Shuffle the tensor. It is shuffled by default along the first dimension.
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 4,  5],
       [ 3,  6]], dtype=int32)>

### Other ways to make tensors

In [14]:
tf.ones([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [15]:
tf.zeros(shape=(3,5))

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

You can also turn numpy arrays into tensors.

The main difference between numpy arrays and tensorflow is that tensors can be run on GPUs (much faster for numerical computing).


In [20]:
import numpy as np

# Tensors are often denoted by capital letters (X) and vectors as small letters (y).

numpy_A = np.arange(1,25, dtype=np.int32)
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [21]:
A.ndim

3

### Getting information from tensors

- Shape
- Rank
- Axis or dimension
- Size

In [23]:
# Create a rank-4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [24]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [25]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

### Get various attributes of the tensors

In [35]:
print('Datatype of every element of the tensor:', rank_4_tensor.dtype)
print('Number of dimensions (rank):', rank_4_tensor.ndim)
print('Shape of the tensor:', rank_4_tensor.shape)
print('Elements along the 0th axis:', rank_4_tensor.shape[0])
print('Elements along the last axis:', rank_4_tensor.shape[-1])
print('Total number of elements in the tensor:', tf.size(rank_4_tensor))
# Size converted to numpy.
print('Total number of elements in the tensor:', tf.size(rank_4_tensor).numpy())

Datatype of every element of the tensor: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of the tensor: (2, 3, 4, 5)
Elements along the 0th axis: 2
Elements along the last axis: 5
Total number of elements in the tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in the tensor: 120


### Indexing tensors

Tensors can be indexed as python lists.

In [36]:
some_list = [3, 4, 5, 7]
some_list[:2]

[3, 4]

In [37]:
# Get the first 2 elements of each dimension of the tensor.
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [44]:
# Get the first element of each dimension from each index, except the last one.
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [45]:
# Create a rank 2 tensor.
rank_2_tensor = tf.constant([[2, 1],
                             [4, 5]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [46]:
# Get the last item of each row of our tensor.
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 5], dtype=int32)>

In [48]:
# Add in an extra dimension to our rank 2 tensor.
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [1]],

       [[4],
        [5]]], dtype=int32)>

In [50]:
# Alternative way to add extra axis.
tf.expand_dims(rank_2_tensor, axis=-1)   # -1 means that the final axis should be expanded

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [1]],

       [[4],
        [5]]], dtype=int32)>

In [51]:
tf.expand_dims(rank_2_tensor, axis = 0)   # Expand the 0th axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[2, 1],
        [4, 5]]], dtype=int32)>

### Manipulating the tensor (tensor operations)

Basic operations: '+', '-', '*', '/'

In [56]:
tensor = tf.constant([[10, 3], 
                      [6, 7]])
tensor + 10

# The original tensor does not change.

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 13],
       [16, 17]], dtype=int32)>

In [57]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  30],
       [ 60,  70]], dtype=int32)>

In [58]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -7],
       [-4, -3]], dtype=int32)>

In [59]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  30],
       [ 60,  70]], dtype=int32)>

In [62]:
tensor / 5

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2. , 0.6],
       [1.2, 1.4]])>

### Matrix multiplication

This is one the most common operations.

In [64]:
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  3]
 [ 6  7]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[118,  51],
       [102,  67]], dtype=int32)>

In [67]:
A = tf.constant([[1, 2, 5], [7, 2, 1], [3, 3, 3]])
B = tf.constant([[3, 5], [6, 7], [1, 8]])
tf.matmul(A, B)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [68]:
# Alternative way of matrix multiplication:
A @ B

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [69]:
Y = tf.constant([[2, 3], 
                 [3, 4], 
                 [1, 3]])
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 3],
       [4, 1, 3]], dtype=int32)>

In [70]:
A @ Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[13, 26],
       [21, 32],
       [18, 30]], dtype=int32)>

In [71]:
# Transposed matrix.
tf.transpose(Y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 1],
       [3, 4, 3]], dtype=int32)>

In [73]:
# Note that transpose() and reshape() change the matrix structure but in a different way.
Y, tf.transpose(Y), tf.reshape(Y, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 3],
        [3, 4],
        [1, 3]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[2, 3, 1],
        [3, 4, 3]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[2, 3, 3],
        [4, 1, 3]], dtype=int32)>)

In [76]:
# An alternative way for matrix multiplication.
tf.tensordot(A, B, axes=[[1], [0]])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

### Changing the datatype of a tensor

In [78]:
# Create a new tensor with default datatype.
B = tf.constant([1.5, 6.7])
B.dtype

tf.float32

In [79]:
C = tf.constant([3, 5])
C.dtype

tf.int32

In [82]:
# Change from int32 to int16 (this is called reduced precision).
# 32 bit precision is the default one, but to increase speed or efficiency in model training, but decrease precision, we can use 16 bit.

D = tf.cast(B, dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.5, 6.7], dtype=float16)>

In [84]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 5.], dtype=float32)>

### Aggregating tensors

In [87]:
# Get the absolute value
D = tf.constant([-10, -7])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [90]:
# Create a random tensor with values between 0 and 100 and size=50.
import numpy
E = tf.constant(numpy.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([16, 15, 73, 28, 63, 80, 14,  7,  4, 26,  5, 18, 24, 58, 17, 38, 82,
       89, 22, 64, 39,  3, 96, 27, 24, 84, 56, 79, 56, 34, 99, 52, 72, 35,
       61, 30, 84, 81, 44, 77, 44, 98, 57, 81, 32, 98, 38,  5, 65, 18])>

In [92]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [93]:
# Find minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [94]:
# Find maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [95]:
# Find the mean.
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [96]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2412>

In [107]:
# Find the variance
# Note that you must convert the datatype to float first! In this case you also have to use tf.math...
E = tf.cast(E, dtype=tf.float32)
tf.math.reduce_variance(E)

<tf.Tensor: shape=(), dtype=float32, numpy=851.6224365234375>

In [110]:
# Find the standard deviation
# Note that the datatype must be float! In this case you also have to use tf.math...
tf.math.reduce_std(E)

<tf.Tensor: shape=(), dtype=float32, numpy=29.182571411132812>

### Positional maximum and minimum

In [111]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [113]:
# Find the positional maximum - the index with the biggest value
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [114]:
# Find the corresponding value
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [115]:
# Is it equal to the max value
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [116]:
# Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [117]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>

### Squeezing a tensor (removing single dimensions)

In [118]:
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [119]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
       0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
       0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
       0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
       0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
       0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
       0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
       0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
       0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
       0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
      dtype=float32)>

### One hot encoding

In [123]:
# Create a list of indices
some_list = [0, 1, 2, 3]
tf.one_hot(some_list, depth=4, on_value='wow', off_value='mmmmmmmmmm')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'wow', b'mmmmmmmmmm', b'mmmmmmmmmm', b'mmmmmmmmmm'],
       [b'mmmmmmmmmm', b'wow', b'mmmmmmmmmm', b'mmmmmmmmmm'],
       [b'mmmmmmmmmm', b'mmmmmmmmmm', b'wow', b'mmmmmmmmmm'],
       [b'mmmmmmmmmm', b'mmmmmmmmmm', b'mmmmmmmmmm', b'wow']],
      dtype=object)>

### Squaring, log, square root

In [125]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [126]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [128]:
# The method requires non-int type data.
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [130]:
# The method requires non-int type data.
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and numpy

In [131]:
# Create a tensor directly from a numpy array.
J = tf.constant(np.array([3., 5., 4.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 5., 4.])>

In [132]:
# Convert the tensor to numpy.
np.array(J), type(np.array(J))

(array([3., 5., 4.]), numpy.ndarray)

In [133]:
# Convert the tensor to numpy
J.numpy(), type(J.numpy())

(array([3., 5., 4.]), numpy.ndarray)

In [134]:
J = tf.constant([3.])
J.numpy()[0]

np.float32(3.0)

In [136]:
# The default types of each are slightly different.
numpy_J = tf.constant(np.array([3., 5., 7.]))
tensor_J = tf.constant([3., 5., 7.])
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPU

In [137]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]